spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/db_test?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: hocgin
    initialization-mode: ALWAYS


#logging:
#  config: classpath:log4j2-local.yml
logging:
  level:
    in.hocg: debug
